install.packages('ggplot2')
library(ggplot2)
data(msleep)
library(downloader)
url="https://raw.githubusercontent.com/genomicsclass/dagdata/master/inst/extdata/msleep_ggplot2.csv"
filename <- basename(url)
download(url,filename)
read.csv(msleep_ggplot2.csv)
class(msleep_ggplot2.csv)
dat <- read.csv("msleep_ggplot2.csv")
class(dat)
dat2 <- filter(dat, order=="Primates")
head(dat)
nrow(dat2)
library(dplyr)
class(dat2)
control <- dat2 %>% select (sleep_total) %>% unlist(dat2) 
mean(control)
control2 <- dat2 %>% select(sleep_total) %>% summarise(mean(sleep_total)) 
filter(dat, order=="Primates") %>% summarise( mean( sleep_total) )
library()